export enum Status {
          OK = "OK",
          CREATED ="CREATED",
          BAD_REQUEST = "BAD_REQUEST",
          UNAUTHORIZED = "UNAUTHORIZED",
          NOT_FOUND = "NOT_FOUND",
          UNPROCESSABLE_ENTITY = "UNPROCESSABLE_ENTITY",
          INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
          FORBIDDEN = "FORBIDDEN"
}